# Generated by Django 5.2.3 on 2025-07-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.JSONField(blank=True, null=True)),
                ('account_details', models.JSONField(blank=True, null=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
