# Generated by Django 5.1.1 on 2025-07-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_productcategory_category_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='amount',
            new_name='offer_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
    ]
