# Generated by Django 5.1.1 on 2025-07-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_amount_offer_offer_amount_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_percentage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
