# Generated by Django 5.1.1 on 2025-07-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_offer_offer_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_amount',
            field=models.IntegerField(null=True),
        ),
    ]
