# Generated by Django 5.1.1 on 2025-07-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_offer_offer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
