# Generated by Django 5.1.1 on 2025-07-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_offer_offer_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_name',
            field=models.TextField(unique=True),
        ),
    ]
