# Generated by Django 5.1.1 on 2025-07-09 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_offer_offer_amount_alter_offer_offer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyEarning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_earning', models.DateField()),
                ('earning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userprofile')),
                ('payment_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.paymentmode')),
            ],
        ),
    ]
