# Generated by Django 5.1.1 on 2025-07-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_userprofile_otp_deliveryotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_id',
            new_name='email',
        ),
    ]
