# Generated by Django 5.1.1 on 2025-08-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_userprofile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursPay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyearning',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='attendence',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.paymentmode'),
        ),
        migrations.AlterField(
            model_name='dailyearning',
            name='earning',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hours_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.hourspay'),
        ),
    ]
